namespace Demo.DDD.SystemTests.Setup
{
    static class SecurityConfigurationProvider
    {
        public const string IssuerSigningKey =
            "MIICkzCCAXsCBgF7YzguKTANBgkqhkiG9w0BAQsFADANMQswCQYDVQQDDAJvazAeFw0yMTA4MjAxMDU4NTFaFw0zMTA4MjAxMTAwMzFaMA0xCzAJBgNVBAMMAm9rMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoDv66rt3iuL1LNgY9y4o8itZk808Wphq+Blr5xRsrCe7/cToR2YzMUPE1paf32ypEJMac2q3UUwxLipGxmzU52VVElGVWXBtRcJMY8XrsRt+Usa3woD1rxtRoaY2BIGpfgzpOFX/DmGYf4302MkHn6d789aa/GhsHObo+jTjwsn4386yTyaVyRUryVN9sqmo9Xih1i1QBxx52MFeuChP8eVCm8VTo2UiwfGrEWsD9Q1K0jKwKC8RsR+GlHERBXXL3qmblf2WJ4NylmwucXpCUO7fPpourREewCnTPaQzUdcv0R2tPfiOJsC/GDs5f5tgD1VDJkK4PjKacP/STA1S9QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCZQIwef3p6qqfNKOOwsc4tY9JIIqzEmZojV0MhulgbDsepX4HB+PlPiVhb4zYZhIrmBfGxoFBlp8o0Xy2xwPawsWInY8ak2hz2yHE6F/Q2CsgoGV9tkWLCrYJNO9nMlYkoaEeEFrGwfcc2G2LCOoyfHX3v5J3bJZXeUBvuOA855DzguhALqHpSnndAysfLxWBGY+yP0coPXxK168nGoJQlpGiK+ELGMy407a6bIZ2kdZ4FaZEzaLUkJKRJlw0Td9s6KvPX61Cm7m/xzHq8d8t15ZlrhaQOztaON7s3QC5s+MDLQtHITuHnm+TcYIGstynVKO4H/t3gByBNe6Xc6pSv";

        public const string OpenIdConfiguration =
            @"{""issuer"":""http://localhost:8080/auth/realms/ok"",""authorization_endpoint"":""http://localhost:8080/auth/realms/ok/protocol/openid-connect/auth"",""token_endpoint"":""http://localhost:8080/auth/realms/ok/protocol/openid-connect/token"",""token_introspection_endpoint"":""http://localhost:8080/auth/realms/ok/protocol/openid-connect/token/introspect"",""userinfo_endpoint"":""http://localhost:8080/auth/realms/ok/protocol/openid-connect/userinfo"",""end_session_endpoint"":""http://localhost:8080/auth/realms/ok/protocol/openid-connect/logout"",""jwks_uri"":""http://localhost:8080/auth/realms/ok/protocol/openid-connect/certs"",""check_session_iframe"":""http://localhost:8080/auth/realms/ok/protocol/openid-connect/login-status-iframe.html"",""grant_types_supported"":[""authorization_code"",""implicit"",""refresh_token"",""password"",""client_credentials""],""response_types_supported"":[""code"",""none"",""id_token"",""token"",""id_token token"",""code id_token"",""code token"",""code id_token token""],""subject_types_supported"":[""public"",""pairwise""],""id_token_signing_alg_values_supported"":[""PS384"",""ES384"",""RS384"",""HS256"",""HS512"",""ES256"",""RS256"",""HS384"",""ES512"",""PS256"",""PS512"",""RS512""],""userinfo_signing_alg_values_supported"":[""PS384"",""ES384"",""RS384"",""HS256"",""HS512"",""ES256"",""RS256"",""HS384"",""ES512"",""PS256"",""PS512"",""RS512"",""none""],""request_object_signing_alg_values_supported"":[""PS384"",""ES384"",""RS384"",""ES256"",""RS256"",""ES512"",""PS256"",""PS512"",""RS512"",""none""],""response_modes_supported"":[""query"",""fragment"",""form_post""],""registration_endpoint"":""http://localhost:8080/auth/realms/ok/clients-registrations/openid-connect"",""token_endpoint_auth_methods_supported"":[""private_key_jwt"",""client_secret_basic"",""client_secret_post"",""client_secret_jwt""],""token_endpoint_auth_signing_alg_values_supported"":[""RS256""],""claims_supported"":[""aud"",""sub"",""iss"",""auth_time"",""name"",""given_name"",""family_name"",""preferred_username"",""email""],""claim_types_supported"":[""normal""],""claims_parameter_supported"":false,""scopes_supported"":[""openid"",""address"",""email"",""microprofile-jwt"",""offline_access"",""phone"",""profile"",""roles"",""web-origins""],""request_parameter_supported"":true,""request_uri_parameter_supported"":true,""code_challenge_methods_supported"":[""plain"",""S256""],""tls_client_certificate_bound_access_tokens"":true,""introspection_endpoint"":""http://localhost:8080/auth/realms/ok/protocol/openid-connect/token/introspect""}";

        public const string JsonWebKeySet =
            "{\"keys\":[{\"kid\":\"DhvAVQFsGpvBlNBo7sN4Fc457pNhsaq1hz5tsjT9qkI\",\"kty\":\"RSA\",\"alg\":\"RS256\",\"use\":\"sig\",\"n\":\"oDv66rt3iuL1LNgY9y4o8itZk808Wphq-Blr5xRsrCe7_cToR2YzMUPE1paf32ypEJMac2q3UUwxLipGxmzU52VVElGVWXBtRcJMY8XrsRt-Usa3woD1rxtRoaY2BIGpfgzpOFX_DmGYf4302MkHn6d789aa_GhsHObo-jTjwsn4386yTyaVyRUryVN9sqmo9Xih1i1QBxx52MFeuChP8eVCm8VTo2UiwfGrEWsD9Q1K0jKwKC8RsR-GlHERBXXL3qmblf2WJ4NylmwucXpCUO7fPpourREewCnTPaQzUdcv0R2tPfiOJsC_GDs5f5tgD1VDJkK4PjKacP_STA1S9Q\",\"e\":\"AQAB\",\"x5c\":[\"MIICkzCCAXsCBgF7YzguKTANBgkqhkiG9w0BAQsFADANMQswCQYDVQQDDAJvazAeFw0yMTA4MjAxMDU4NTFaFw0zMTA4MjAxMTAwMzFaMA0xCzAJBgNVBAMMAm9rMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoDv66rt3iuL1LNgY9y4o8itZk808Wphq+Blr5xRsrCe7/cToR2YzMUPE1paf32ypEJMac2q3UUwxLipGxmzU52VVElGVWXBtRcJMY8XrsRt+Usa3woD1rxtRoaY2BIGpfgzpOFX/DmGYf4302MkHn6d789aa/GhsHObo+jTjwsn4386yTyaVyRUryVN9sqmo9Xih1i1QBxx52MFeuChP8eVCm8VTo2UiwfGrEWsD9Q1K0jKwKC8RsR+GlHERBXXL3qmblf2WJ4NylmwucXpCUO7fPpourREewCnTPaQzUdcv0R2tPfiOJsC/GDs5f5tgD1VDJkK4PjKacP/STA1S9QIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCZQIwef3p6qqfNKOOwsc4tY9JIIqzEmZojV0MhulgbDsepX4HB+PlPiVhb4zYZhIrmBfGxoFBlp8o0Xy2xwPawsWInY8ak2hz2yHE6F/Q2CsgoGV9tkWLCrYJNO9nMlYkoaEeEFrGwfcc2G2LCOoyfHX3v5J3bJZXeUBvuOA855DzguhALqHpSnndAysfLxWBGY+yP0coPXxK168nGoJQlpGiK+ELGMy407a6bIZ2kdZ4FaZEzaLUkJKRJlw0Td9s6KvPX61Cm7m/xzHq8d8t15ZlrhaQOztaON7s3QC5s+MDLQtHITuHnm+TcYIGstynVKO4H/t3gByBNe6Xc6pSv\"],\"x5t\":\"0Ac3h0Pb4XjvI9IS7ln0aLPTU4Q\",\"x5t#S256\":\"wtALoQ0MazNM26DiFd1kvkxDqePQvqrQdzACfIq-o5o\"}]}";
    }
}
